### ISSUE TITLE
Volume stats missing

### ISSUE THREAD

**Issue by kibs** [digitalocean/csi-digitalocean#134]
### What did you do? (required. The issue will be **closed** when not provided.)
Setup kube-prometheus (https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus)

### What did you expect to happen?
Being able to see PV stats, like diskspace free etc. There is an dashboard for this already added, but data was empty. Checked out prometheus data and didn't find any metrics named kubelet_volume_stats_*

Searched around, and it looks like from my understanding that the driver should implement this.

https://stackoverflow.com/questions/44718268/how-to-monitor-disk-usage-of-kubernetes-persistent-volumes?rq=1

* CSI Version:
latest managed DO cluster

* Kubernetes Version:
1.3.14 managed DO cluster

**Comment by mkcl-dev** [comment]
I'm facing the same situation (DO-managed k8s 1.3.14). No volume metrics are exposed.

```
$ curl -skH 'Authorization: Bearer ...' https://10.xxx.xxx.xxx:10250/metrics | grep ^kubelet_volume | wc -l
0
```

Related info: [coreos/prometheus-operator#2359](https://github.com/coreos/prometheus-operator/issues/2359)

Having suffered from a volume with no space left on device just recently I'd like to hear if there's any update on this issue.

**Comment by boedy** [comment]
In need of the same requirement. Critical to have the ability to send alerts if volume is reaching full capacity.

Willing to contribute through PR. Some guidance where to start would be helpful though. @fatih any suggestions?

**Comment by timoreimann** [comment]
I have finished what I think should approach a working implementation of the requested frdtuet. Still need to run more tests to confirm.
