### ISSUE TITLE
Question: Are non-DigitalOcean nodes supported?

### ISSUE THREAD

**Issue by ryanmjacobs** [digitalocean/csi-digitalocean#138]
Hi,

My apologies if this has been documented or asked before, but I couldn't find any answers online.

Are non-DigitalOcean Kubernetes nodes supported at all? On my cluster, I have two on-premise servers and two DigitalOcean nodes. For some reason, my on-premise nodes never sync successfully.

```console
kube-system   pod/coredns-fb8b8dccf-sphl6    1/1     Running            0     14h
kube-system   pod/csi-do-controller-0        5/5     Running            0     14h
kube-system   pod/csi-do-node-cg76c          0/2     CrashLoopBackOff   275   12h
kube-system   pod/csi-do-node-fgcpg          2/2     Running            0     13h
kube-system   pod/csi-do-node-mn2kf          0/2     CrashLoopBackOff   275   12h
kube-system   pod/csi-do-node-vgllz          2/2     Running            0     14h
```

---

Here are some dumps from kubectl:
```console
ryan@delta ~/w/deployment/kubernetes $ kubectl -n kube-system describe pod/csi-do-node-cg76c | tail -n6
Events:
  Type     Reason   Age                   From                   Message
  ----     ------   ----                  ----                   -------
  Normal   Pulled   41m (x143 over 12h)   kubelet, 10-10-233-83  Successfully pulled image "digitalocean/do-csi-plugin:v1.0.0"
  Warning  BackOff  11m (x3524 over 12h)  kubelet, 10-10-233-83  Back-off restarting failed container
  Warning  BackOff  86s (x3058 over 12h)  kubelet, 10-10-233-83  Back-off restarting failed container
```

```console
ryan@delta ~/w/deployment/kubernetes $ kubectl -n kube-system logs pod/csi-do-node-cg76c csi-node-driver-registrar
I0407 15:29:10.145117       1 main.go:111] Version: v1.0.1-0-g27703026
I0407 15:29:10.145253       1 main.go:118] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0407 15:29:10.145277       1 connection.go:69] Connecting to /csi/csi.sock
I0407 15:29:10.145586       1 connection.go:96] Still trying, connection is CONNECTING
I0407 15:29:10.145860       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
I0407 15:29:11.145866       1 connection.go:96] Still trying, connection is CONNECTING
I0407 15:29:11.145940       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
I0407 15:29:12.187895       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
I0407 15:29:13.364304       1 connection.go:96] Still trying, connection is CONNECTING
I0407 15:29:13.364454       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE

...  this goes on forever ...
```

```console
ryan@delta ~/w/deployment/kubernetes $ kubectl -n kube-system logs pod/csi-do-node-cg76c csi-do-plugin
2019/04/07 15:28:48 couldn't get metadata: Get http://169.254.169.254/metadata/v1.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

---

I'm not sure who `169.254.169.254` is... StackOverflow says that the IP is a "reserved link-local address" (https://stackoverflow.com/a/42315582). So I'm guessing that DigitalOcean nodes virtually resolve this to the block storage server in their datacenter.

If my guess is correct, and foreign nodes aren't supported, is there anyway to block `csi-do-node` from my non-Digitalocean nodes? I'm no expert at Kubernetes, but I think tainting the nodes would do the trick, but I don't want to have to add an exception to every single pod except.

---

Also, maybe we could add a more user-friendly error for the unresolved IP `169.254.169.254`? This caused me headaches for the past two days. It was only now, while writing this, that I realized that this was reserved linked-local IP.

**Comment by ryanmjacobs** [comment]
Okay, back again. I think I found a decent fix. I just added a `nodeSelector` that selects only my DigitalOcean nodes. I had to label my DO nodes with `kubectl label nodes <node 1> <node 2> digitalocean=true`.

```diff
diff --git a/csi-digitalocean-v1.0.0.yaml b/csi-digitalocean-v1.0.0.yaml
index c7ebbd4..24553d0 100644
--- a/csi-digitalocean-v1.0.0.yaml
+++ b/csi-digitalocean-v1.0.0.yaml
@@ -420,6 +420,9 @@ spec:
         app: csi-do-node
         role: csi-do
     spec:
+      nodeSelector:
+        digitalocean: "true"
+
       priorityClassName: system-node-critical
       serviceAccount: csi-do-node-sa
       hostNetwork: true
```

Hopefully this has no repurcusions? I'm not sure if other if my other non-digitalocean nodes will be able to access the PVCs... If someone could let me know, that would be fantastic.

**Comment by pluqueTheLuxe** [comment]
Hey guys, we are having the same exact issue here. As opposed to @ryanmjacobs, our k8s cluster is completly on-prem. 

I was looking to use the do-csi driver for the provisionning of my pv's.

So since I have no k8s nodes in DO, @ryanmjacobs fix will not work. 

any tips? corrections?

**Comment by timoreimann** [comment]
The CSI driver only supports managing DigitalOcean volumes, which by nature do not work on any other cloud or (on-prem) environment.

I think the canonical way to accomplish what you're looking for is to leverage the storage provider available in your on-prem environment. Storage classes are meant to provide that distinction. Your on-prem PVCs would need to specify the proper class, and workloads would reference PVCs accordingly based on what kind of node they run on.

The metadata service is a common kind of service implemented by many clouds. It usually provides environmental configuration data; in our case, it's the droplet ID that we retrieve and subsequently leverage in order to attach volumes to the right nodes.

I'm happy to improve the error message. Will keep the issue open until that has happened.
