### ISSUE TITLE
Can't create new volume via DO CSI driver

### ISSUE THREAD

**Issue by kycfeel** [digitalocean/csi-digitalocean#139]
### What did you do? (required. The issue will be **closed** when not provided.)

Trying to create a new volume via DO-CSI. But It stucks on pending status forever. 

```
$ kubectl describe pvc <VOLUME_NAME>--namespace <NAMESPACE>
Name:          <VOLUME_NAME>-
Namespace:   <NAMESPACE>
StorageClass:  do-block-storage
Status:        Pending
Volume:
Labels:        <none>
Annotations:   control-plane.alpha.kubernetes.io/leader={"holderIdentity":"e991ffcf-5b6b-11e9-b0bc-0a580af40242","leaseDurationSeconds":15,"acquireTime":"2019-04-10T08:47:45Z","renewTime":"2019-04-10T09:06:00Z","lea...
               kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"hollaex-testnet-postgres-volume","namespace":"hollaex"},"spec":{...
               volume.beta.kubernetes.io/storage-provisioner=com.digitalocean.csi.dobs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type     Reason                Age                 From                                                                                Message
  ----     ------                ----                ----                                                                                -------
  Normal   ExternalProvisioning  3m (x302 over 18m)  persistentvolume-controller                                                         waiting for a volume to be created, either by external provisioner "com.digitalocean.csi.dobs" or manually created by system administrator
  Warning  ProvisioningFailed    1m (x5 over 15m)    com.digitalocean.csi.dobs csi-do-controller-0 e991ffcf-5b6b-11e9-b0bc-0a580af40242  Failed to provision volume with StorageClass "do-block-storage": timed out waiting for the condition
  Normal   Provisioning          50s (x6 over 18m)   com.digitalocean.csi.dobs csi-do-controller-0 e991ffcf-5b6b-11e9-b0bc-0a580af40242  External provisioner is provisioning volume for claim "<NAMESPACE>/ <VOLUME_NAME>"
```

From `csi-do-plugin-0` =

```
...

I0410 09:10:16.866057       1 controller.go:106] GRPC response: 
I0410 09:10:16.866127       1 controller.go:107] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
W0410 09:10:16.866175       1 controller.go:354] CreateVolume timeout: 10s has expired, operation will be retried

...
```

And never stop to print this error.

DO CSI worked fine with this setup exactly even just few hours ago. and suddenly this started to happens.

How can I fix this? Is this a known bug?

### What did you expect to happen?

Get a new clean volume

### Configuration (**MUST** fill this out):

* system logs:

Please provide the following logs:

```

kubectl cluster-info dump > kubernetes-dump.log
```

This will output everthing from your cluster.  Please use a private gist via
https://gist.github.com/ to share this dump with us

* manifests, such as pvc, deployments, etc.. you used to reproduce:

Please provide the **total** set of manifests that are needed to reproduce the
issue. Just providing the `pvc` is not helpful. If you cannot provide it due
privacy concerns, please try creating a reproducible case.

* CSI Version: 0.2.0

* Kubernetes Version: 1.11.6
 
* Cloud provider/framework version, if applicable (such as Rancher):
General DO droplets on SGP1, cluster built with kubeadm.

**Comment by carlhopf** [comment]
same issue here on a fresh cluster v1.13.5

**Comment by buztard** [comment]
I'm pretty sure it's caused by https://status.digitalocean.com/incidents/1ptrlnshssy0 - not by the CSI driver.

**Comment by ChSch3000** [comment]
I encountered the same issue today. CSI driver was working until this morning, now we are not able to create any volume neither upgrade our deployments

**Comment by kycfeel** [comment]
I'm also pretty sure this issue happened cause of temporary DO API error. After they announced the issue has been solved on https://status.digitalocean.com/incidents/1ptrlnshssy0, I can create new volumes without errors.
