### ISSUE TITLE
csi-do Pod not created successfully, socket connection hangs

### ISSUE THREAD

**Issue by jadesrochers** [digitalocean/csi-digitalocean#178]
### What did you do? (required. The issue will be **closed** when not provided.)

Created a new Kubernetes v1.14.6 three host cluster (master & two nodes) using kubeadm. 
Used this config file as the --config argument to kubeadm init:
```apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServer:
  extraArgs:
    feature-gates: "VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true"
    allow-privileged: "true"

networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "192.168.0.0/16"
---

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
FeatureGates: 
  VolumeSnapshotDataSource: true
  KubeletPluginsWatcher: true
  CSINodeInfo: true
  CSIDriverRegistry: true
---
```

Installed Calico 3.7 as the CNI plugin, also installed Helm/Tiller.
After creating the cluster, I added/accessed/removed test pods (like busybox) just to make sure it was working, and it seemed fine.

I used the instructions at https://github.com/digitalocean/csi-digitalocean to then try and get the CSI-do plugin working.
I re-installed the cluster and csi-do driver several times trying to make sure I have followed all the instructions, but have not been able to get it to work.

#### The csi-do pods get stuck with a CreateContainerConfigError:
Relevant output from kubectl get pods -A:
kube-system   csi-do-controller-0                              3/4     CreateContainerConfigError   0          91m
kube-system   csi-do-node-8bv8s                                1/2     CreateContainerConfigError   0          91m
kube-system   csi-do-node-kj5pt                                1/2     CreateContainerConfigError   0          91m

#### Sample of logs for csi-do-controller-0  csi-provisioner container:
I0819 19:27:48.908808       1 feature_gate.go:226] feature gates: &{map[]}
I0819 19:27:48.909181       1 csi-provisioner.go:95] Version: v1.1.0-0-gcecb5a96
I0819 19:27:48.909375       1 csi-provisioner.go:109] Building kube configs for running in cluster...
I0819 19:27:48.935545       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0819 19:27:58.936788       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0819 19:28:08.936291       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
The "Still connecting" line then repeats regularly.

##### The attacher logs:
I0819 19:27:50.316519       1 main.go:91] Version: v1.1.1-0-g0d83c92
I0819 19:27:50.320264       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0819 19:28:00.320568       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

##### snapshotter logs: 
I0819 19:27:52.204987       1 main.go:89] Version: v1.1.0-0-gac339597
I0819 19:27:52.234927       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0819 19:28:02.235345       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

###### csi-do-plugin logs:
Error from server (BadRequest): container "csi-do-plugin" in pod "csi-do-controller-0" is waiting to start: CreateContainerConfigError

#### I believe I correctly configured kubelet and API server options/ features gates:

From the systemctl output for the kubelet service:
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf --feature-gates=VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true

The API server command I accessed through ps aux indicates --allow-privileged=true and --feature-gates=VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true

### What did you expect to happen?
The csi-do pods would start successfully and I would be able to create a pvc.

### Configuration (**MUST** fill this out):

* system logs:

Please provide the following logs:

```

kubectl cluster-info dump > kubernetes-dump.log
```

#### Here is the cluster-info dump:
https://gist.github.com/jadesrochers/5943957237b553ac4664b86d5e4c62e8

* manifests, such as pvc, deployments, etc.. you used to reproduce:

#### I used these manifests on the cluster creation run I am showing output for:
calico and csi-do manifests, the secret required for access to my do account and the pvc. 

https://docs.projectcalico.org/v3.7/manifests/calico.yaml

https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.1.1.yaml

Secret:
apiVersion: v1
kind: Secret
metadata:
  name: digitaloceanat1
  namespace: kube-system
stringData:
  access-token: "my-token-here"

PVC:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage

* CSI Version:
https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.1.1.yaml
* Kubernetes Version:
1.14.6
* Cloud provider/framework version, if applicable (such as Rancher):
Digitalocean droplets running Ubuntu 18.04.3, kernel 4.15.0-58-generic

**Comment by snormore** [comment]
Hi @jadesrochers 👋 — I'm seeing events with message `Error: secret "digitalocean" not found` in your cluster info dump for the `csi-do-node` pods. It looks like you might be missing the `digitalocean` secret https://github.com/digitalocean/csi-digitalocean#1-create-a-secret-with-your-digitalocean-api-access-token

**Comment by jadesrochers** [comment]
That was it, thank you for pointing me toward it. At some point in the process I altered the name of the secret so it was no longer digitalocean, and failed to notice the secret was not being found. Once that was fixed, it worked immediately.
Thanks again.
