### ISSUE TITLE
Persistent Volume With Deployment, Stuck after node unready

### ISSUE THREAD

**Issue by phucvinh52** [digitalocean/csi-digitalocean#186]
Hi team,
I have a problem need describe, please help.
I created a deployment (mysql) with persistent volume claim on cluster k8s (digitalocean) with 2 nodes (Node A &B).
The problem that i got, pod is scheduled to Node A, then some reason Node A stopped. But pod could not running to NodeB.
![image](https://user-images.githubusercontent.com/16432970/66101841-7c25e400-e5da-11e9-8509-e542fb8b7ffa.png)
And describe pod on NodeB.
```
Multi-Attach error for volume "pvc-30c134ca-377c-4c29-8000-7e29c0850b7e" Volume is already used by pod(s) io-mysql-7f4fdf4c66-n6788
```
I used lastest version k8s (1.15.3-do.3) on Digitalocean.
Thank team, an give me an advice if you have.

**Comment by snormore** [comment]
Hi there! The `Multi-Attach error for volume` event is usually a transient event that should resolve after a few minutes, after a few attempts by the controller. Did that happen in this case or is it still hanging with that event?

**Comment by phucvinh52** [comment]
Hi @snormore ,
I wait more than 30 mins in previous cluster, and i just has created new cluster but still stuck
![image](https://user-images.githubusercontent.com/16432970/66117499-ea7c9d80-e5fe-11e9-9a08-fb7ad049a3ff.png).
Note: I stopped (not remove) Node where pod run on it.

**Comment by snormore** [comment]
Ah I see, since the node still exists the volume is still attached to it. This can be resolved with one of the following options:
 1. delete the node so that the volume is detached from it and can be attached to another, or
 2. delete the VolumeAttachment instance via `kubectl delete volumeattachment <name>`

**Comment by phucvinh52** [comment]
@snormore 
Thanks for your information, do you have any a plan auto deattched volume for this case in the future.

**Comment by snormore** [comment]
In this case I believe the behaviour of not detaching automatically when a droplet is stopped is appropriate. The reason we don't auto-detach the volume when the droplet is stopped (vs being destroyed), is that we can't assume that the user will not start the node again expecting the volume to still be attached.

**Comment by phucvinh52** [comment]
Thank for your all information @snormore
