### ISSUE TITLE
Build using Go 1.13

### ISSUE THREAD

**Issue by timoreimann** [digitalocean/csi-digitalocean#187]
We should update the build-related files (Makefile, Travis, possibly also go.mod) to ensure that the latest Go 1.13 is used for building CSI. It's probably not worth building on any older Go versions since CSI is a binary and does not need to maintain backwards compatibility.

The most notable change from Go 1.12 to 1.13 is that `GO111MODULE`'s default value of `auto` now enables module-ware mode if a `go.mod` file is found. See also the [relevant section in the Go 1.13 change log](https://golang.org/doc/go1.13#modules).

A [similar change in our CCM repository](https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/279) might be helpful as a pattern to implement the change.

**Comment by akashsharma95** [comment]
would like to take this up

**Comment by timoreimann** [comment]
@akashsharma95 thanks, please do! Let us know if you have any questions.

**Comment by jayapriya90** [comment]
@timoreimann Updated csi to build using Go 1.13. Could I get your review please: https://github.com/digitalocean/csi-digitalocean/pull/194

**Comment by timoreimann** [comment]
This was implemented successfully.
