### ISSUE TITLE
Support for Raw Block Volume mounts

### ISSUE THREAD

**Issue by graham-web** [digitalocean/csi-digitalocean#192]
We're looking at running a Rook.io / Ceph cluster backed by DigitalOcean block storage, as a means to achieve ReadWriteMany persistent volumes.

Currently, it appears csi-digitalocean does not support attaching a Block Storage volume as a block mode PV, which is required to use Rook's '[Storage Class Device Sets](https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#storage-class-device-sets)' feature.

Is raw block volume support planned?

Ref:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support
https://kubernetes-csi.github.io/docs/raw-block.html

**Comment by adamwg** [comment]
We should be able to support this pretty easily. There's no change needed in the controller - block volume creation will happen the same way regardless of whether a volume is going to be used in `Block` or `Mount` mode. We do need a change in the node driver, which currently assumes `Mount` mode.

Not sure when we'll get to this, but I'll create a ticket internally at DO to track it. Of course, if anyone in the community would like to take this on we would welcome the contribution.

**Comment by timoreimann** [comment]
Support for raw block volumes got merged into master. It will be shipped with the next release.
