### ISSUE TITLE
v1.1.2 not found image "quay.io/k8scsi/csi-attacher:v1.1.2"

### ISSUE THREAD

**Issue by IbraevM** [digitalocean/csi-digitalocean#195]
In the [manifests v1.1.2](https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v1.1.2.yaml) `csi-attacher` use image tag `v1.1.2`. But this tag not found in [Repository Tags](https://quay.io/repository/k8scsi/csi-attacher) and kubelet say: 

>  Failed to pull image "quay.io/k8scsi/csi-attacher:v1.1.2": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/k8scsi/csi-attacher:v1.1.2 not found

Change tag `1.1.1` for `csi-attacher` solves the problem.

**Comment by timoreimann** [comment]
Thanks for reporting. It seems like the version bump was due to our [Makefile being a tad too aggressively](https://github.com/digitalocean/csi-digitalocean/blob/bea29c29d555d8026025694c42394073c3b6d77c/Makefile#L27).

We'll fix the wrong image tag specifier (and update our release logic).

**Comment by timoreimann** [comment]
Master now contains the right csi-attacher version (v1.1.1).
