### ISSUE TITLE
Align k8s digitalocean token secret name with cloud-controller-manager

### ISSUE THREAD

**Issue by peterver** [digitalocean/csi-digitalocean#20]
There is a difference in the name between how digitalocean/cloud-controller-manager calls the secret that holds the k8s digitalocean token, and the way the secret is named here. Leading to two secrets with different names in k8s.

Is it possible to align these ?

**Comment by fatih** [comment]
Hi @peterver 

This is a valid concern. I'll change it to `digitalocean` so it's in sync with CCM because CCM was created before and the CSI plugin is still not widely adopted.

**Comment by peterver** [comment]
@fatih we've got a use-case where we're using both CCM and CSI at the same time for persistent volumes and claims and it was just something I noticed :).  Thanks for the quick action !
