### ISSUE TITLE
Feature Request: Report disk usage for volumes from this driver

### ISSUE THREAD

**Issue by jacksontj** [digitalocean/csi-digitalocean#203]
I was attempting to add some monitoring around my volume usage today and I found that I don't have them in my cluster. After some looking it appears that it is the responsibility of the csi driver to expose those metrics (https://github.com/google/cadvisor/issues/1702#issuecomment-538337013).

So assuming that is accurate (there are similar issues for other csi plugins, e.g. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/223) -- then this is me requesting this be added to the digitalocean csi driver.

**Comment by timoreimann** [comment]
Hi there @jacksontj 

You're right that CSI driver is responsible for providing (certain) metrics. Specifically, the gRPC endpoint [`NodeGetVolumeStats`](https://github.com/container-storage-interface/spec/blob/4731db0e0bc53238b93850f43ab05d9355df0fd9/spec.md#nodegetvolumestats) is supposed to provide data around byte and inode capacity.

I believe your request is a duplicate of #134. If you agree, then I'd like to close this issue.

The good news is that we have PR #197 in-flight right now that is going to ship support for the statistics endpoint described above. We are aiming for a new release of our CSI driver soon after that PR has merged. DOKS is planned to incorporate the CSI update on our next, internal release cycle.

Hope this helps.

**Comment by jacksontj** [comment]
My apologies for missing that other issue, this definitely is a dupe. I'll go ahead and close this out
