### ISSUE TITLE
Resize PVC doesn't complete. Resizes all objects _except_ PVC.

### ISSUE THREAD

**Issue by therealkevinard** [digitalocean/csi-digitalocean#288]
### What did you do? (required. The issue will be **closed** when not provided.)
Following the steps in [Volume Expansion](https://github.com/digitalocean/csi-digitalocean/blob/master/README.md#volume-expansion), I applied a manifest to resize an existing PVC by 10GB.

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs-server-provisioner-0
  namespace: infrastructure
spec:
  resources:
    requests:
      storage: 210Gi
```

### What did you expect to happen?
- pvc/data-nfs-server-provisioner-0 resize from 200Gi to 210GI
- (underlying) pv/pvc-943a5e3b-0e72-429b-9058-31747e17c0d8 resize from 200Gi to 210GI
- (do console) volume pvc-943a5e3b-0e72-429b-9058-31747e17c0d8 resize from 200Gi to 210GI

#### Instead:
The PVC doesn't resize, but the pv and DO volume do.

The relevant PVC event message seems to be `Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.`
Also, in Conditions, there's a message `FileSystemResizePending True ... Waiting for user to (re-)start a pod to finish file system resize of volume on node.` This isn't documented, and I've had much trouble in the past with volume re-attaching do-block-storage volumes after restarting a pod, so I'm a little wary of doing so here (without confirmation, at least)    

Full `describe`
```text
$ kubectl describe pvc/data-nfs-server-provisioner-0 pv/pvc-943a5e3b-0e72-429b-9058-31747e17c0d8
Name:          data-nfs-server-provisioner-0
Namespace:     infrastructure
StorageClass:  do-block-storage
Status:        Bound
Volume:        pvc-943a5e3b-0e72-429b-9058-31747e17c0d8
Labels:        app=nfs-server-provisioner
               release=nfs-server-provisioner
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-nfs-server-provisioner-0","namespace":"infrast...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      200Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    nfs-server-provisioner-0
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 27 Feb 2020 09:18:22 -0500           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                    Age   From                                        Message
  ----     ------                    ----  ----                                        -------
  Warning  ExternalExpanding         56m   volume_expand                               Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                  56m   external-resizer dobs.csi.digitalocean.com  External resizer is resizing volume pvc-943a5e3b-0e72-429b-9058-31747e17c0d8
  Normal   FileSystemResizeRequired  56m   external-resizer dobs.csi.digitalocean.com  Require file system resize of volume on node


Name:            pvc-943a5e3b-0e72-429b-9058-31747e17c0d8
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
Finalizers:      [kubernetes.io/pv-protection external-attacher/dobs-csi-digitalocean-com]
StorageClass:    do-block-storage
Status:          Bound
Claim:           infrastructure/data-nfs-server-provisioner-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        210Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            dobs.csi.digitalocean.com
    VolumeHandle:      74461385-4dc5-11ea-880b-0a58ac1473de
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=1581531748985-8081-dobs.csi.digitalocean.com
Events:                <none>

```

### Configuration (**MUST** fill this out):
* system logs:
https://gist.github.com/therealkevinard/51ed25937b5fb6e07db52366b43f98d8

* manifests, such as pvc, deployments, etc.. you used to reproduce:
https://gist.github.com/therealkevinard/51ed25937b5fb6e07db52366b43f98d8

* CSI Version:
    ```
    1.2.0
    ```

* Kubernetes Version:
    ```
    Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
    ```

* Cloud provider/framework version, if applicable (such as Rancher):
    ```
    RKE, rancher 2.3.2
    ```

**Comment by timoreimann** [comment]
👋

We officially support resizing in beta only. Before 1.16, it was still marked alpha and needed special gates flags. Does Rancher add those?
Would you possibly have a chance to test with Kubernetes 1.16 as well?

**Comment by therealkevinard** [comment]
Okay, it works like a charm on 1.16.7 :smile: No downtime, no trouble with volumes mounting, no problems at all.   
We can close this out, unless you have anything to add/note?

---
For posterity - and for anyone who comes into the same trouble - what I did: 
- Upgrade k8s version via RKE to 1.16.7 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Re-apply the volume expansion. I used a slightly higher size than before to make sure it was an "expansion" on all fronts - I used 220Gi instead of the original 210Gi 
- Gave it a minute or two, then exec-ed into the nfs pod and `df -h` was in-line with 220Gi. 
- Did the same, using 250Gi - `df -h` in the nfs pod checks-out again (reads 246G now)

Maybe the extra size-bumps were overkill, but I wanted to avoid any inconsistencies and whatnot.

**Comment by timoreimann** [comment]
Thanks for confirming that things work fine on 1.16. I'll be closing the issue then.

By the way, the newest CSI driver release should also fix a few things with regards to reattaching volumes after pod restarts / moving across nodes. If you still see issues, please don't hesitate to submit a DO support ticket. I'm eager to track down and eliminate any bugs we may still have remaining.
