### ISSUE TITLE
I get provisioning failed unable to authenticate

### ISSUE THREAD

**Issue by hcabnettek** [digitalocean/csi-digitalocean#29]
I have a valid token, added as a secret per the docs. When I kubectl describe pvc/csi-pvc, I get the error message `StorageClass "do-block-storage": rpc error: code = Internal desc = GET https://api.digitalocean.com/v2/volumes?name=pvc-xxx&region=sfo2: 401 Unable to authenticate you`. doctl work with this token without issue.

**Comment by fatih** [comment]
Hi @hcabnettek 

Unfortunately I cannot reproduce it (I'm using the same secret and examples.) 

Can you check out the logs of the provisioner and attacher? Example:

```
$ kubectl -n kube-system logs pods/csi-provisioner-doplugin-0 digitalocean-csi-plugin 
$ kubectl -n kube-system logs pods/csi-attacher-doplugin-0 digitalocean-csi-plugin 
```

These will output in json format, you can pipe it to [humanlog](https://github.com/aybabtme/humanlog) to have a better representation, i.e:

```
$ kubectl -n kube-system logs pods/csi-provisioner-doplugin-0 digitalocean-csi-plugin | humanlog
$ kubectl -n kube-system logs pods/csi-attacher-doplugin-0 digitalocean-csi-plugin | humanlog
```

**Comment by peterver** [comment]
@hcabnettek can you log into kubernetes and see if your token has any content ? I had that happen where the secret was created but due to a nesting issue in my yaml file didn’t have any content

**Comment by hcabnettek** [comment]
@peterver yes when I get the secret, pipe it to base64 --decode, it decodes to the correct key. I notice the namespace for the secret is 'kube-system' should it be 'default'?

**Comment by peterver** [comment]
@hcabnettek in case you are using the 0.0.1 release, please set the secret in the default namespace :), in case you are using the 0.1 release it should be in the kube-system namespace.

**Comment by fatih** [comment]
This is weird. Everything seems normal, I definitely think the CSI plugin gets a token that is not valid. Could it be that it's empty somehow?

What does the following gives you? :

```
$ kubectl get secrets/digitalocean -n kube-system -o json
```

**Comment by andrewsykim** [comment]
fwiw I had a similar problem and it was because I didn't update my secret properly. Make sure the key is also updated from `token` -> `access-token`.

**Comment by hcabnettek** [comment]
@fatih it seems to get it correctly
{
    "apiVersion": "v1",
    "data": {
        "access-token": "MGFlZGUyYWEwZWUzMGE5OWE3MjA4ZWFlN2Y0MGNkZjMzNzMxNWI0MWJmZDFlZTYwOGYyODkwNWQwMGU0ZDU0MQ=="
    },
    "kind": "Secret",
    "metadata": {
        "creationTimestamp": "2018-05-16T00:13:12Z",
        "name": "digitalocean",
        "namespace": "kube-system",
        "resourceVersion": "515778",
        "selfLink": "/api/v1/namespaces/kube-system/secrets/digitalocean",
        "uid": "eb9757c2-589d-11e8-9065-ba83f38d01da"
    },
    "type": "Opaque"
}

**Comment by hcabnettek** [comment]
Closing this issue. I created a new droplet and cluster using centos and kubespray. Everything seems to work. The pvc is bound and the pv is created.
