### ISSUE TITLE
MountVolume.MountDevice failed for volume

### ISSUE THREAD

**Issue by AATHITH** [digitalocean/csi-digitalocean#297]
### What did you do?
I created a redis statefulset with PV.
I deleted the pod(not stateful set just the pod) to check the data persistence.
The recreated pod is stuck at **ContainerCreating**.

### What did you expect to happen?
I want that pod to run after it was recreated from deletion.

### Configuration (**MUST** fill this out):

```
kubectl describe po csi-do-controller-0 -n kube-system
MountVolume.SetUp failed for volume "csi-do-controller-sa-token-x5thl" : failed to sync secret cache: timed out waiting for the condition
```
```
root@k8-master-01:~/redis# k describe po redis-0
Name:           redis-0
Namespace:      default
Priority:       0
Node:           k8-worker-01/ip
Start Time:     Tue, 07 Apr 2020 13:52:08 +0530
Labels:         app=redis
                controller-revision-hash=redis-df6bf67f8
                statefulset.kubernetes.io/pod-name=redis-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/redis
Containers:
  redis:
    Container ID:  
    Image:         redis
    Image ID:      
    Port:          6379/TCP
    Host Port:     0/TCP
    Command:
      redis-server
      /root/redis.conf
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /root/redis.conf from config (rw,path="redis.conf")
      /var/lib/redis/6379 from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bmswz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis-data
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redis-conf
    Optional:  false
  default-token-bmswz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bmswz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                  From                   Message
  ----     ------       ----                 ----                   -------
  Warning  FailedMount  60m (x13 over 114m)  kubelet, k8-worker-01  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config default-token-bmswz]: timed out waiting for the condition
  Warning  FailedMount  55m (x6 over 105m)   kubelet, k8-worker-01  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config default-token-bmswz data]: timed out waiting for the condition
  Warning  FailedMount  50m (x33 over 115m)  kubelet, k8-worker-01  MountVolume.MountDevice failed for volume "pvc-edd053ea-6eed-4763-85d5-046d7bb6238c" : rpc error: code = Internal desc = mounting failed: exit status 255 cmd: 'mount -t ext4 /dev/disk/by-id/scsi-0DO_Volume_pvc-edd053ea-6eed-4763-85d5-046d7bb6238c /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-edd053ea-6eed-4763-85d5-046d7bb6238c/globalmount' output: "mount: mounting /dev/disk/by-id/scsi-0DO_Volume_pvc-edd053ea-6eed-4763-85d5-046d7bb6238c on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-edd053ea-6eed-4763-85d5-046d7bb6238c/globalmount failed: Resource busy\n"
  Warning  FailedMount  41m (x2 over 43m)    kubelet, k8-worker-01  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config default-token-bmswz data]: timed out waiting for the condition
  Warning  FailedMount  15m (x23 over 45m)   kubelet, k8-worker-01  MountVolume.MountDevice failed for volume "pvc-edd053ea-6eed-4763-85d5-046d7bb6238c" : rpc error: code = Internal desc = mounting failed: exit status 255 cmd: 'mount -t ext4 /dev/disk/by-id/scsi-0DO_Volume_pvc-edd053ea-6eed-4763-85d5-046d7bb6238c /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-edd053ea-6eed-4763-85d5-046d7bb6238c/globalmount' output: "mount: mounting /dev/disk/by-id/scsi-0DO_Volume_pvc-edd053ea-6eed-4763-85d5-046d7bb6238c on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-edd053ea-6eed-4763-85d5-046d7bb6238c/globalmount failed: Resource busy\n"
  Warning  FailedMount  9m56s (x5 over 37m)  kubelet, k8-worker-01  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-bmswz data config]: timed out waiting for the condition
  Warning  FailedMount  5m25s (x9 over 39m)  kubelet, k8-worker-01  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config default-token-bmswz]: timed out waiting for the condition
```

* manifests, such as pvc, deployments, etc.. you used to reproduce:
https://github.com/AATHITH/blog/tree/master/kubernetes/redis

* CSI Version: 1.2.0

* Kubernetes Version: 1.16

* Cloud provider/framework version, if applicable: Digitalocean cloud

**Comment by AATHITH** [comment]
Restarted the Worker node in which that stateful pod was running. The entered running state. I want to know the reason to avoid this kind of situations in the future.

**Comment by timoreimann** [comment]
👋

Before digging into this one: what's the `csi-do-controller-0` you reference in the issue description? Its name looks similar to the CSI controller part of the driver. However, that should not exist on the worker nodes as we have it running in the DOKS control plane. Concurrently running multiple controller instances could lead to problems potentially similar to what you are seeing.

**Comment by AATHITH** [comment]
I'm running kubernetes as my own cluster in the Digital ocean(not managed k8 by DO)

**Comment by timoreimann** [comment]
@AATHITH gotcha 👍 I suppose you run the controller as a StatefulSet?

"Device busy" sounds like the device is already in use somehow. It'd be good to know what the individual CSI components were doing before and when the volume was mounted.

Could you please share the logs of the following components:

- the CSI driver in the controller
- the following sidecars from the controller: provisioner, attacher
- the CSI driver from all worker nodes
- the kubelet from all worker nodes

Thanks.

**Comment by AATHITH** [comment]
I have created DO-csi with this [link](https://github.com/digitalocean/csi-digitalocean)
all CSI and kubelet related logs are here in this [repo](https://github.com/AATHITH/do-csi-logs.git)

**Comment by henninge** [comment]
I have probably run into the same problem. In my case, the "Resource busy" is caused by this mount:
`/mnt/.do-first-mount-bITtYIeQX /dev/sda  ext4   ro,relatime,data=ordered`

It only happens on the *second* time that the volume is attached to the node. Steps to reproduce:

1. Create a PVC with the do-block-storage class.

**Comment by timoreimann** [comment]
@henninge thanks for chiming in and for providing the detailed repro steps. That was very useful, we might have an idea as to what could be causing this. We'll do some digging and report back.

In the meantime, could you (and @AATHITH) do me a favor and let me know which DOKS version your cluster is running on exactly (i.e., something like 1.16.6-do.2)? Thanks!

**Comment by henninge** [comment]
@timoreimann  Glad I could help. I forgot to mention three further steps.

9. Manually unmount  /mnt/.do-first-mount-xxxxx
10. The node plugin completes and the pod starts.
11. Subsequent detach/attach sequences work fine without the /mnt/.do-first-mount-xxxxx reappearing.

I was using plain Kubernetes 1.18.2 on two droplets (a master & a worker), no additional feature gates were active as all features required in the driver doc are now enabled by default.

**Comment by AATHITH** [comment]
> @henninge thanks for chiming in and for providing the detailed repro steps. That was very useful, we might have an idea as to what could be causing this. We'll do some digging and report back.
> 
> In the meantime, could you (and @AATHITH) do me a favor and let me know which DOKS version your cluster is running on exactly (i.e., something like 1.16.6-do.2)? Thanks!

I'm using a self-managed Kubernetes cluster(1 master and 2 worker nodes) running in k8s:v1.16.8

**Comment by timoreimann** [comment]
Ah, good to know you're running self-managed clusters. In that case, you can to fix the problem yourself.

It looks like the error is caused by DigitalOcean's built-in auto-format udev rule that detects unformatted devices and briefly mounts them to format the file-system. Given unfortunate timing, it could conflict with the CSI driver also trying to mount a device.

Our CSI driver comes with its own logic to initially format a device, so we do not even need the udev rule (that was designed to help with bootstrapping block storage on vanilla/unmanaged droplets). What you can try to do as a workaround for now is remove the file located at

```
/etc/udev/rules.d/99-digitalocean-automount.rules
```

from each of your workers. A simple Daemonset or something installed natively on your self-managed worker nodes could presumably do that trick.

Let me know how that goes.

**Comment by henninge** [comment]
Works like a charm! Thank you!

(I added the removal to the node startup script.)

**Comment by timoreimann** [comment]
Thanks for the confirmation. Glad to hear it's working!

I'll keep the ticket open to extend our official deployment manifests similarly.

**Comment by klausenbusk** [comment]
> The rule is not needed for DOKS, however, and we (DO) should disable it long-term.

Is there any ETA on removing the logic? It is a bit annoying.
