### ISSUE TITLE
startup instructions need to be updated for the 2.0.0 release. 

### ISSUE THREAD

**Issue by dustymabe** [digitalocean/csi-digitalocean#331]
### What did you do? (required. The issue will be **closed** when not provided.)

I noticed that the documentation seems to be wrong. The [documentation](https://github.com/digitalocean/csi-digitalocean/tree/f1ca95d18b590187b60967b71182dba42cbcdad6#2-deploy-the-csi-plugin-and-sidecars) says to:

```
kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-vX.Y.Z.yaml
```

But for the latest release 2.0.0 it seems like the artifacts were broken out into three separate files so the instructions now longer work. See the 3 files under https://github.com/digitalocean/csi-digitalocean/tree/f1ca95d18b590187b60967b71182dba42cbcdad6/deploy/kubernetes/releases/csi-digitalocean-v2.0.0

### What did you expect to happen?

Instructions work.

**Comment by timoreimann** [comment]
Thanks for reporting @dustymabe. I submitted a PR, reviews are welcome if you like to. 💙
