### ISSUE TITLE
Is anyone experience the DigitalOcean CSI driver for using with Nomad ?

### ISSUE THREAD

**Issue by scorsi** [digitalocean/csi-digitalocean#362]
Hello,

I don't understand how to use the CSI driver with Nomad.

I looked here (it's more or less the only resources available about that feature online) : 
 - https://www.nomadproject.io/docs/job-specification/csi_plugin
 - https://www.nomadproject.io/docs/internals/plugins/csi
 - https://www.hashicorp.com/blog/hashicorp-nomad-container-storage-interface-csi-beta (for AWS)
 - https://learn.hashicorp.com/tutorials/nomad/stateful-workloads-csi-volumes?in=nomad/stateful-workloads#deploy-the-ebs-plugin (the more interesting one but.. for AWS)

When looking on Google, it seems nobody did that (or at least share its experience). It may be very easy to do, but I never did that so I'm totally lost here.

I wanted to know if someone did use (or did have idea on how to use) CSI driver with Nomad and if he could share the steps with me ?

Thanks,

**Comment by timoreimann** [comment]
Unfortunately I cannot answer the question. What I do know is that we had one DigitalOcean customer reporting an issue that led to me filing hashicorp/nomad#8358, so at least someone once tried to use the driver with Nomad. :)

If this is still relevant, I'd encourage to reach out to the Nomad community. Happy to take any PRs that may amend our documentation to help Nomad users use DO's CSI driver more easily.

**Comment by scorsi** [comment]
For thoses falling here, HashiCorp did an exemple here : https://github.com/hashicorp/nomad/tree/master/demo/csi/digitalocean
