### ISSUE TITLE
PVCs frequently stuck in terminating

### ISSUE THREAD

**Issue by rbren** [digitalocean/csi-digitalocean#365]
### What did you do? (required. The issue will be **closed** when not provided.)
Created, then deleted a PVC.

[Full repro instructions here](https://github.com/FairwindsOps/gemini/tree/master/examples/hackmd). Others have run into the same problem when following those instructions (per a recent PR on that repo).

### What did you expect to happen?
The PVC gets deleted. 

Instead, the `delete` command hangs. If I `ctrl-C`, the pvc shows its status as `Terminating` forever. I need to edit the finalizers to remove it.

FWIW the corresponding volume appears to have been deleted in the DO UI.

### Configuration (**MUST** fill this out):

The csi-do-node pods keep outputting the same line:
```
csi-do-node-b42bl csi-do-plugin time="2020-11-05T11:31:52Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc:<type:STAGE_UNSTAGE_VOLUME > " node_id=214264468 region=nyc1 version=v1.1.2
csi-do-node-7hzdx csi-do-plugin time="2020-11-05T11:32:06Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc:<type:STAGE_UNSTAGE_VOLUME > " node_id=187241696 region=nyc1 version=v1.1.2
csi-do-node-b42bl csi-do-plugin time="2020-11-05T11:32:07Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc:<type:STAGE_UNSTAGE_VOLUME > " node_id=214264468 region=nyc1 version=v1.1.2
csi-do-node-7hzdx csi-do-plugin time="2020-11-05T11:32:08Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc:<type:STAGE_UNSTAGE_VOLUME > " node_id=187241696 region=nyc1 version=v1.1.2
csi-do-node-b42bl csi-do-plugin time="2020-11-05T11:32:13Z" level=info msg="node get capabilities called" method=node_get_capabilities node_capabilities="rpc:<type:STAGE_UNSTAGE_VOLUME > " node_id=214264468 region=nyc1 version=v1.1.2
```

* system logs:

```
kubectl cluster-info dump > kubernetes-dump.log
```
> Lots of personal information here. Hesitant to share given how easy this is to repro, but lmk if it's necessary.

* manifests, such as pvc, deployments, etc.. you used to reproduce:

> See detailed repro link above

* CSI Version: `quay.io/k8scsi/csi-node-driver-registrar:v1.2.0`

* Kubernetes Version: 1.16.2

* Cloud provider/framework version, if applicable (such as Rancher): Vanilla DO Cluster

**Comment by timoreimann** [comment]
@rbren which version of the CSI driver are you using? you specified just the version of the registrar.

(The log output indicates v1.1.2, though I remember we had a bug once where the wrong version was reported.)

Can you please confirm that you run the driver in version 1.3.0 (the latest, compatible version for Kubernetes 1.16) and if not, try again with that version first? A fair amount of fixes came with that.

**Comment by rbren** [comment]
Thanks for the quick response Timo!

What's the right way to check my version (and update if it's not 1.3)? I'm just using whatever came out of the box when I spun up my cluster

**Comment by timoreimann** [comment]
@rbren oh this is a managed Kubernetes cluster? Sorry, saw _vanilla_ in the description and thought of self-managed.

**Comment by rbren** [comment]
Ah sorry, yeah I see the confusion there :) Yeah it's a managed DO cluster

**Comment by timoreimann** [comment]
@rbren thanks for confirming.

You are indeed running CSI driver in version v1.1.2. Would you mind upgrading your DOKS cluster to at least the latest 1.16 patch version? That you give you the v1.3.0 CSI release. If the problems continue to persist after the upgrade, we can totally dig deeper.

**Comment by DataFire-repos** [comment]
I could swear I was able to reproduce once after upgrading, but after several attempts today everything seems to be working well.

I think it's safe to close this - thanks for the help!

**Comment by rbren** [comment]
I could swear I was able to reproduce once after upgrading, but after several attempts today everything seems to be working well.

I think it's safe to close this - thanks for the help!
