### ISSUE TITLE
Issue creating VolumeSnapshots

### ISSUE THREAD

**Issue by rbren** [digitalocean/csi-digitalocean#370]
### What did you do? (required. The issue will be **closed** when not provided.)
* Start a new cluster on DO (today, with default settings)
* Create a PVC
* Create a VolumeSnapshot for that PVC (works)
  * shown as "ready" in 2-3 seconds
* Create a second VolumeSnapshot for that PVC (doesn't work)
  * hangs as "not ready" indefinitely

I don't see anything in the CSI logs related to VolumeSnapshot creation or management. Both snapshots
have the same events:

### Working
```
Status:
  Bound Volume Snapshot Content Name:  snapcontent-55176500-c667-448c-a6fe-6abac2495881
  Creation Time:                       2020-12-07T14:49:02Z
  Ready To Use:                        true
  Restore Size:                        2Gi
Events:
  Type    Reason            Age    From                 Message
  ----    ------            ----   ----                 -------
  Normal  CreatingSnapshot  8m18s  snapshot-controller  Waiting for a snapshot notepad/new-snapshot-test to be created by the CSI driver.
```

### Broken
```
Status:
  Bound Volume Snapshot Content Name:  snapcontent-2323bd58-cc2f-486a-827b-2ae282613634
  Ready To Use:                        false
Events:
  Type    Reason            Age    From                 Message
  ----    ------            ----   ----                 -------
  Normal  CreatingSnapshot  6m49s  snapshot-controller  Waiting for a snapshot notepad/new-snapshot-test-3 to be created by the CSI driver.
```

### What did you expect to happen?
A second VolumeSnapshot should work

### Configuration (**MUST** fill this out):

* system logs: https://gist.github.com/rbren/b94db387de0dc9c849a3ee85dbe8385c

* manifests, such as pvc, deployments, etc.. you used to reproduce:

```
helm install hackmd stable/hackmd -n notepad --version "2.0.*" --set postgresql.postgresqlPassword=thisisnotasecret
```
gives me a couple PVCs. I then used this manifest to create snapshots
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test-3
spec:
  source:
    persistentVolumeClaimName: hackmd
```
changing the name each time

* CSI Version: `docker.io/digitalocean/do-csi-plugin:v2.1.1`

* Kubernetes Version: 1.19.3

* Cloud provider/framework version, if applicable (such as Rancher): N/a

**Comment by rbren** [comment]
🤔 it looks like this might be due to ratelimiting? It seems like the snapshot might be ready after 10m. Trying to verify now.

**Comment by timoreimann** [comment]
@rbren yes you're right, this is due to rate limiting. The [public docs have this documented as a known issue](https://www.digitalocean.com/docs/images/snapshots/#limits).

If this is on DOKS, then we might not expose the error too well at this point. This is something we plan to improve on.

**Comment by rbren** [comment]
👍 perfect yeah, I think that's exactly what I'm hitting. Thanks!
