### ISSUE TITLE
Feature Request: Expanding Persistent Volumes Claims

### ISSUE THREAD

**Issue by Zatvobor** [digitalocean/csi-digitalocean#39]
Hi there. As I can see, it is not implemented yet (maybe I'm wrong). I would like to ask you, what the priority of that? Also, would be great to see the project roadmap 👍 

Thanks

**Comment by fatih** [comment]
Hi @Zatvobor,

The CSI plugin doesn't know anything about Kubernetes related terms. What exactly do you mean by this request? Bonus points if you can provide some reproducible files for me.

**Comment by fatih** [comment]
Closing this due to the lack of feedback. Please feel free to reopen if needed. Thanks.
