### ISSUE TITLE
Issue with CSI outside of DigitalOcean droplets

### ISSUE THREAD

**Issue by landingpage21** [digitalocean/csi-digitalocean#460]
Im facing issue trying to install CSI and use it in none DigitalOcean droplets, I have pass --region and --token as mentioned in Doc but still facing issue : 

> couldn't get droplet ID from metadata: Get "http://169.254.169.254/metadata/v1/id": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (are you running outside of a DigitalOcean droplet?)

**Comment by adamwg** [comment]
DigitalOcean block storage can be attached only to DigitalOcean Droplets. It is not possible to use the DigitalOcean CSI driver with non-DO nodes.
