### ISSUE TITLE
Cannot apply csi driver on cis-1.23 hardened rke2 

### ISSUE THREAD

**Issue by jhoelzel** [digitalocean/csi-digitalocean#517]
Hey there,
Im unable to install the csi driver on a hardneded rke2 cluster that is following selinux and csi guidelines.
My goal is to use the wunderfull block storage of do instead of the space on the nodes.
The process seems to be stopping and the initialization container directly, because there is no way for the container to stat  '/etc/udev/rules.d/99-digitalocean-automount.rules' which is likely because of selinux.

### What did you do? (required. The issue will be **closed** when not provided.)

`kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v4.6.1/{crds.yaml,driver.yaml,snapshot-controller.yaml}`

### What did you expect to happen?

CSI driver installing itself on a hardened rke2 cluster which is cis-compliant.
I would like to operate hardened nodes, while also using DO block storage for my dynamic storage solutions.

### Configuration (**MUST** fill this out):

i changed nothing but installted the defaults. I of course added the DO token as a secret to the same namespace.

`kubectl logs csi-do-node-76f6z -n kube-system
Error from server (BadRequest): container "csi-do-plugin" in pod "csi-do-node-76f6z" is waiting to start: PodInitializing
`
```
`kubectl logs csi-do-node-76f6z -n kube-system -c automount-udev-deleter
rm: can't stat '/etc/udev/rules.d/99-digitalocean-automount.rules': Permission denied
```

* CSI Version:

v4.6.1

* Kubernetes Version:

Client Version: v1.25.11+rke2r1
Kustomize Version: v4.5.7
Server Version: v1.25.11+rke2r1

* Cloud provider/framework version, if applicable (such as Rancher):
default RKE2

**Comment by timoreimann** [comment]
Hi 👋 

I also think this is probably connected to SELinux and how it affects the default permission schema. My experience with SELinux is limited, a quick Google though yielded https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container which I wonder might be necessary?

**Comment by timoreimann** [comment]
@jhoelzel I wonder if, as a workaround to the host mount, you could inject something through cloud-init / user data that deletes the udev file as well. That way, you don't need to do it via the CSI pod.

Another alternative could be to bake similar logic into a custom droplet / VM base image. Probably not great from a maintenance point though.

This may be best solved at the storage / droplet layer, perhaps through a new API field to suppress the udev addition. Feel free to file a support ticket with DO for that as I think it's not fully in scope of what this repo should be tracking.

**Comment by timoreimann** [comment]
@jhoelzel what I meant was that when you create the droplets, you could extend the user data portion to have a script that deletes the udev file. I think the droplet API offers a way to interact with cloud init in this fashion.

I believe this would be independent of any addressing that DO drove.
