### ISSUE TITLE
Make sure functions are idempotent

### ISSUE THREAD

**Issue by fatih** [digitalocean/csi-digitalocean#7]

**Comment by ritoon** [comment]
What kind of storage you have ? This could be a middleware with that connect to a redis cluster ?

**Comment by fatih** [comment]
@ritoon I didn't understand what you mean? Can you clarify what this has to do with the issue? Thanks

**Comment by ritoon** [comment]
@fatih I was just trying to help you on this open issue, but didn't figure out that this wasn't ``http.Request`` idempotency but rather function execution idempotency. Where do you need this check is it [here](https://github.com/digitalocean/csi-digitalocean/blob/master/driver/node.go#L159)? Could it be done with a hash of the reflect values used on the func ``Mount`` and then this hash would be stored in a map? Anyway, I'll be happy to help if any need.

**Comment by fatih** [comment]
@ritoon I've pushed to master some changes that uses linux tools to achieve it. let's see how that works, we can always change it if needed.
