### ISSUE TITLE
AttachVoume.Attach failed for voume: node has no NodeID annotation

### ISSUE THREAD

**Issue by fatrix** [digitalocean/csi-digitalocean#79]
### What did you do? 
* Installed csi-digitalocean-v0.2.0 on Kubernetes 1.11.2
* Created PersistentVolumeClaim
* Added volume to a Pod

### What did you expect to happen?
* Volume is mounted into Pod

### What happend

* DO volume is created

* v1/PersistentVolumeClaim is bound

    my-volume1  Bound   pvc-xxxx   5Gi       RWO           do-block-storage  48m

* Pod does not start

    AttachVolume.Attach failed for volume "pvc-xxxx" : node "kubernetes-node-ng-1" has no NodeID annotation
Unable to mount volumes for pod "db-xxxx/xxx-xx_mynamespace(xxxx-xxxx-xxxx-xxx-xxxx)": timeout expired waiting for volumes to attach or mount for pod "mynamespace"/"db-xxxx". list of unmounted volumes=[my-volume1]. list of unattached volumes=[plone-volume1 default-token-xxxx]

### Configuration (**MUST** fill this out):

* CSI Version: 0.2.0

* Kubernetes Version: 1.11.2

* Cloud provider/framework version, if applicable (such as Rancher):

Plain Kubernetes deployed with kubeadm

**Comment by fatih** [comment]
Can you share the logs please? It's lacking. It was part of the issue template. If you can't share the full logs please share the following:

```
kubectl logs -l role=csi-do -c csi-do-plugin -n kube-system 
```

**Comment by fatrix** [comment]
Sorry ok, this output is less smaller: https://gist.github.com/fatrix/a1f3db1471920b67bfdca2db4df39f2c

**Comment by fatih** [comment]
It seems like it can't mount it to the node. Is it possible some of your nodes are unhealthy? what does this give:

```
kubectl get nodes -o wide
```

Or better please share the following command:

```
kubectl cluster-info dump > kubernetes-dump.log
```

or share the kubeconfig with me (mail: farslan at digitalocean dot com) so I can debug it. Thanks

**Comment by fatrix** [comment]
Thank @fatih for your support. Nodes are looking good:

    kubectl get nodes -o wide
    NAME                   STATUS    ROLES     AGE       VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
    kubernetes-master-ng   Ready     master    4d        v1.11.2   46.101.160.145    <none>        CentOS Linux 7 (Core)   3.10.0-862.2.3.el7.x86_64   docker://1.13.1
    kubernetes-node-ng-1   Ready     <none>    4d        v1.11.2   165.227.172.144   <none>        CentOS Linux 7 (Core)   3.10.0-862.2.3.el7.x86_64   docker://1.13.1
    kubernetes-node-ng-2   Ready     <none>    4d        v1.11.2   138.197.184.46    <none>        CentOS Linux 7 (Core)   3.10.0-862.2.3.el7.x86_64   docker://1.13.1
    kubernetes-node-ng-3   Ready     <none>    4d        v1.11.2   46.101.162.98     <none>        CentOS Linux 7 (Core)   3.10.0-862.2.3.el7.x86_64   docker://1.13.1

I will send you the dump by mail.

**Comment by fatrix** [comment]
I see that the csi pod on my first node has problems, it seems like in the issue #58. 

    $ kubectl logs csi-do-node-6p2hs -c driver-registrar --namespace=kube-system
    I0911 19:53:36.298644       1 main.go:120] Version: v0.3.0-0-g8dd4550d
    I0911 19:53:36.298726       1 main.go:135] Attempting to open a gRPC connection with: "/csi/csi.sock"
    I0911 19:53:36.298737       1 connection.go:68] Connecting to /csi/csi.sock
    I0911 19:53:36.298906       1 connection.go:95] Still trying, connection is CONNECTING
    I0911 19:53:36.299210       1 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
    I0911 19:53:37.300079       1 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
    I0911 19:53:38.342148       1 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
    I0911 19:53:39.518521       1 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
    ....
    I0911 19:54:36.298919       1 connection.go:88] Connection timed out
    I0911 19:54:36.298958       1 main.go:143] Calling CSI driver to discover driver name.
    I0911 19:54:36.298982       1 connection.go:136] GRPC call: /csi.v0.Identity/GetPluginInfo
    I0911 19:54:36.298992       1 connection.go:137] GRPC request:
    I0911 19:54:36.299083       1 connection.go:139] GRPC response:
    I0911 19:54:36.299142       1 connection.go:140] GRPC error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
    E0911 19:54:36.299158       1 main.go:148] rpc error: code = Unavailable desc = all SubConns are in TransientFailure

**Comment by fatrix** [comment]
Everything is working now.

* allow-privileged flag was not set for kubelets. I had to add `--allow-privileged=true` in  `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` for `KUBELET_KUBECONFIG_ARGS` and then `systemctl restart kubelet`
* shared mount was already allowed.

**Comment by fatih** [comment]
Thanks @fatrix for the kubeconfig. I looked into it and indeed one of the nodes is problematic. It seems like the registar is not able to connect to the node-plugin. However the node-plugin seems to work fine, though there are no logs! This is very interesting. 

For your questions above:

1. You need to add the following flag to your kubelet configuration:

```
kubelet --allow-privileged=true
```

I think this should be already enabled by default in `kubeadm` but I didn't double checked it.

2. This page shows how to check if mount propagation is enabled: https://docs.portworx.com/knowledgebase/shared-mount-propagation.html

**Comment by fatih** [comment]
@fatrix I was just writing a comment and saw that you also commented.  Thanks for letting us know, much appreciated.
