### ISSUE TITLE
Driver does not support reclaimPolicy: Retain 

### ISSUE THREAD

**Issue by ikamman** [digitalocean/csi-digitalocean#8]
Currently the driver always formating volumes before mounting and does not respect reclaimPolicy: Retain.
For the Retain policy the driver should not format volumes and leave any data on them.

**Comment by fatih** [comment]
Thanks @ikamman for the feedback. Please let me know if there is anything else that comes to your mind. We're still working on fleshing out the edge cases, hence it's marked as alpha.

**Comment by fatih** [comment]
Closing this as I don't think this is CSI related. Please feel free to open an issue if this doesn't happen with other CSI drivers, but happens only here. Again, the CSI driver doesn't know anything about any Kubernetes related policy or logic.
