### ISSUE TITLE
Attachment Issues

### ISSUE THREAD

**Issue by ZachGlassman** [digitalocean/csi-digitalocean#81]
### What did you do? (required. The issue will be **closed** when not provided.)
Had problems attaching and detaching pods along with some odd 500 errors during what we later figured was an API outage for Digital Ocean.  We were deleting pods with PVC and creating new pods with PVC and recieving problems with almost all actions.  We were also left in a state where the CSI resources seem to be trying to delete resources that do not exist.

Some of this was due to getting rate limited once these requests started to pile up.

We tried restarting the controller pods and even deleting the whole CSI system and re-installing it, but the problems persisted.

### What did you expect to happen?
Not sure, I think that the API issues caused some problems with this software and I'm not sure that these problems are really preventable.  I am mostly hoping this information can be useful.

### Configuration (**MUST** fill this out):

* system logs:

https://gist.github.com/ZachGlassman/380978ff77b2cf7fdb2560afc954aa1a

* CSI Version: 0.2.0

* Kubernetes Version: 1.11.2

* Cloud provider/framework version, if applicable (such as Rancher):
Plain Kubernetes with kubeadm

**Comment by fatih** [comment]
Thanks @ZachGlassman for the information. Unfortunately the logs are missing. I'm asking for all logs because there is not much I can do with the logs you provided. Please give me all logs via : 

```
kubectl cluster-info dump > kubernetes-dump.log
```

If you don't want to share the logs publicly you can email it to me: fatih at digitalocean dot com. If you feel comfortable, you can also share the kubeconfig with me, that would be the best. 

Thanks

**Comment by fatih** [comment]
From the logs of the initial comment, it seems like it's due this error:

```
I0910 23:49:59.314831       1 csi_handler.go:86] Error processing "csi-a124aceb5dd89b028c1188b975a9488a2aeaf7b1fefadc1d47de402c0b7bf71e": failed to attach: rpc error: code = Unknown desc = POST https://api.digitalocean.com/v2/volumes/a7cad73b-b548-11e8-bc72-0242ac114503/actions: 422 Droplet Cannot attach more than 7 volumes to a single Droplet.
```

@ZachGlassman does the problem still exists, please let me know.

**Comment by fatih** [comment]
Btw, if you can give me your kubeconfig (my email fatih at digitalocean com), I can also debug it myself.

**Comment by devfelipereis** [comment]
I also have a issue when trying to upgrade my app.

![deepinscreenshot_select-area_20181027120942](https://user-images.githubusercontent.com/5348752/47605773-3bdcdf80-d9e1-11e8-813b-e5fe3055dadc.png)

I deployed a simple ghost blog and it's working good. Then I tryied to upgrade and I'm getting this errors.

**Comment by fatih** [comment]
@devfelipereis can you please open a new issue with exact reproducible case (like how did you deployed Ghost?) Not sure if it's related to this or not.

**Comment by devfelipereis** [comment]
@fatih sure... When I come back home I'll create it.
