### ISSUE TITLE
DO client plugin uses private network, unable to reach DO API

### ISSUE THREAD

**Issue by marinintim** [digitalocean/csi-digitalocean#83]
### What did you do?

Created a cluster in DO with private networking between the nodes, using private IP as apiserver advertising address, then followed the instructions in the README (created secret, applied yaml, created csi-pvc).

After that PVC exists, but PV doesn't get created, and claim remains in the pending state indefinitely .

### What did you expect to happen?

PV gets created.

### Configuration (**MUST** fill this out):

* system logs:

[cluster-info dump](https://gist.github.com/marinintim/a3b8785567b8ece78b0f951b2def5596)

* manifests: directly from the readme, namely: created a secret, then applied csi config, then tried to create a csi-pvc with 5Gi.

* CSI Version: 0.2.0

* Kubernetes Version: 1.11.3

* Cloud provider/framework version, if applicable (such as Rancher): DigitalOcean, installed k8s via latest kubeadm.

### Additional logs

From [the logs of csi-do-plugin](https://gist.github.com/marinintim/afd83598cc5f15daf94eb11ddd9871db) it looks to me that it cannot reach the DO API because it tries to do so over the private network.

**Comment by fatih** [comment]
I just created a cluster with private networking and wasn't able to see any issues:

```
go test -tags integration -v
=== RUN   TestPod_Single_Volume
--- PASS: TestPod_Single_Volume (20.45s)
    integration_test.go:88: Creating pod
    integration_test.go:111: Creating pvc
    integration_test.go:117: Waiting pod "my-csi-app" to be running ...
    integration_test.go:122: Finished!
=== RUN   TestDeployment_Single_Volume
--- PASS: TestDeployment_Single_Volume (11.47s)
    integration_test.go:182: Creating deployment
    integration_test.go:205: Creating pvc
    integration_test.go:229: Waiting pod "my-csi-app-69ccd88fc-hksxl" to be running ...
    integration_test.go:234: Finished!
=== RUN   TestPod_Multi_Volume
--- PASS: TestPod_Multi_Volume (39.58s)
    integration_test.go:290: Creating pod
    integration_test.go:296: Creating pvc1
    integration_test.go:318: Creating pvc2
    integration_test.go:340: Waiting pod "my-multi-csi-app" to be running ...
    integration_test.go:345: Finished!
PASS
ok      github.com/digitalocean/csi-digitalocean/test/kubernetes        72.396s
```

If you can provide me more information or give a kubeconfig for debugging that would be helpful.

Or you can try it yourself. You can exec into the provisioner pod and run the command from there? Here is an example on you can do it

1. First get your secret (we'll need it soon):

```
kubectl get secrets -n kube-system digitalocean -o json | jq -r '.data["access-token"]'| base64 --decode
```

2. Exec into the controller pod:

```
kubectl -n kube-system exec csi-do-controller-0 -c csi-do-plugin -it /bin/sh
```

3. Fix the underlying docker image so we can use doctl:

```
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```

4. Install `doctl`:

```
wget https://github.com/digitalocean/doctl/releases/download/v1.11.0/doctl-1.11.0-linux-amd64.tar.gz
tar xfv doctl-1.11.0-linux-amd64.tar.gz
chmod +x doctl && cp doctl /usr/local/bin
```

5. Validate that it can make requests to DigitalOcean API:

```
DIGITALOCEAN_ACCESS_TOKEN="TOKEN_FROM_STEP_ONE" doctl account get
Email                       Droplet Limit    Email Verified    UUID               Status
yourmailtest@example.com    25               true              717d1d64a39e727    active
```


Let me know what this outputs.

**Comment by fatih** [comment]
Closing this issue due inactivity. Please use the latest version again and let us know if there is anything I can do. Thanks.
