### ISSUE TITLE
Unable to mount a volume in a pod

### ISSUE THREAD

**Issue by did** [digitalocean/csi-digitalocean#89]
### What did you do?

Just followed the instructions from the CSI-DO readme file in order to add a volume to a pod.

### What did you expect to happen?

I should have a pod with the running status and a working mounted volume.
Instead, my pod is in the `ContainerCreating` status.  

Note: The Volume has been correctly created and I can see it in the DO back-office.

### Configuration:

* system logs:

https://gist.github.com/did/39fc1726017e4b7f04343a48fe02b149

* manifests, such as pvc, deployments, etc.. you used to reproduce:

Exactly the same files used in the README.

* CSI Version:

v0.2.0 (https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v0.2.0.yaml)

* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Cloud provider/framework version, if applicable (such as Rancher):

DigitalOcean **without** Rancher. 

**Important:** I'm using the new Kubernetes cluster (in BETA) from DigitalOcean.

Thanks for your help!

**Comment by fatih** [comment]
It seems like the controllers are not able to authenticate to the API:

```
time="2018-10-08T21:54:25Z" level=error msg="method failed" error="GET
https://api.digitalocean.com/v2/volumes/8513dda2-cb3f-11e8-8745-0a58ac144391: 
401 Unable to authenticate you" method=/csi.v0.Node/NodeStageVolume node_id=113975192
region=nyc1 version=v0.2.0
```

This is probably because your token is not valid anymore. Can you please double check it indeed works? A way to quickly test it to call the following commands (assuming you have [doctl](https://github.com/digitalocean/doctl) and [jq](https://stedolan.github.io/jq/) installed): 

```
$ export DIGITALOCEAN_ACCESS_TOKEN=$(kubectl get secrets -n kube-system digitalocean -o json | jq -r '.data["access-token"]'| base64 --decode)
$ doctl compute volume list
```

**Comment by fatih** [comment]
@did is there any chance it's because you created a custom cluster with private networking? There is another open issue here: https://github.com/digitalocean/csi-digitalocean/issues/83 which seems to be related to yours.

**Comment by fatih** [comment]
Btw, if you can give me your kubeconfig (my email fatih at digitalocean com), I can also debug it myself.

**Comment by did** [comment]
@fatih thank you so much for your help! Unfortunately, I've just deleted my DO K8s cluster this morning :-( (I'm testing now AWS for my K8s cluster). 
I'll try to get back to work on my DO installation later this week. Sorry about that :-(

**Comment by fatih** [comment]
@did no worries! Looking forward to fix the issue you have :) If you can reproduce and give me access that would be wonderful, I'm also checking it myself meanwhile.

**Comment by mwthink** [comment]
@fatih I'm currently experiencing this issue on DO, am running with private networking enabled.

**Comment by fatih** [comment]
@mwthink @did can you both try the steps written here: 
https://github.com/digitalocean/csi-digitalocean/issues/83#issuecomment-434637190 I tested it myself with no issues, but I'm curious what the main reason is.

**Comment by timoreimann** [comment]
Seems like the issue has been resolved. If not, please file a new bug report with the most recent version of the CSI plugin installed / DOKS image running.
