### ISSUE TITLE
Error when upgrading workload

### ISSUE THREAD

**Issue by devfelipereis** [digitalocean/csi-digitalocean#98]
### What did you do? (required. The issue will be **closed** when not provided.)
I deployed a blog app using ghost and everything ok here.
Then I did an upgrade just setting a new env value and at this moment I got an error to attach the volume.

### What did you expect to happen?
To upgrade without error when attaching and detaching volumes.

I'm using Rancher 2.0.8

### Configuration (**MUST** fill this out):

* system logs:

Please provide the following logs:

```

kubectl cluster-info dump > kubernetes-dump.log
```

This will output everthing from your cluster.  Please use a private gist via
https://gist.github.com/ to share this dump with us

* manifests, such as pvc, deployments, etc.. you used to reproduce:

![workload](https://user-images.githubusercontent.com/5348752/47965612-73c2d300-e030-11e8-910c-866917370247.jpg)

![volume claim](https://user-images.githubusercontent.com/5348752/47965618-79201d80-e030-11e8-8c8a-e3fe6278e71a.jpg)

![volume](https://user-images.githubusercontent.com/5348752/47965619-7c1b0e00-e030-11e8-978e-17b9a899f0b6.jpg)

![events](https://user-images.githubusercontent.com/5348752/47965623-81785880-e030-11e8-9c03-2aec7fe1189b.jpg)

Everything ok until now.

Now, an upgrade was made just to change an env value. and...

![upgrade events](https://user-images.githubusercontent.com/5348752/47965647-a8cf2580-e030-11e8-8146-a52f2305ff72.jpg)

To fix, I manually deleted the pod.

![manual deleted](https://user-images.githubusercontent.com/5348752/47965651-b5ec1480-e030-11e8-94be-810050b1235e.jpg)

* CSI Version:
 0.2.0

* Kubernetes Version:
1.11.2

* Cloud provider/framework version, if applicable (such as Rancher):
Rancher 2.0.8

**Comment by devfelipereis** [comment]
I also tryed to deploy mysql and I got this:

![mysql](https://user-images.githubusercontent.com/5348752/47965787-71617880-e032-11e8-8667-04316911ca6f.jpg)

Also deleting the pod fix the attaching errors.

**Comment by fatih** [comment]
Thanks @devfelipereis for the info. Seems like if the pod is re-schedule to a **different** node it won't come back. I'll try to debug it with a similar case.

**Comment by fatih** [comment]
I was not able to reproduce this issue with our latest CSI version: `v0.3.1` and Kubernetes `v1.12.1`. The issue I see is that you're running an old version of CSI and K8s which has a bug about re-handling attached volumes. It somehow is not able to attach the volume, but the node still thinks the volume is there. That's why you see the error "... does not exist and no size was specified". 

Can you give me the list of volumeattachments?

```
$ kubectl get volumeattachment
```

You'll see probably more than two here even though you have a single node.

I would suggest to install K8S v1.12.x minimum and our CSI driver `0.3.1`. Also happy to help you if you can share your kubeconfig with me or give ssh access to the nodes. This is my email: fatih at digitalocean dot com

**Comment by devfelipereis** [comment]
Seens that rancher 2.0.8 does not have support for Kubernetes v1.12.1.

I was not aware of the 0.3.1 update. I would like to try it.

About the volumeattachments, I need to deploy again to test. I deleted the lab.

And... I see that rancher stable is now at 2.1.1. So I'll do the upgrade and I come back to tell you about my results.

Thank you!

**Comment by devfelipereis** [comment]
@fatih It's working now.

I did an upgrade to my Rancher and csi-digitalcoean. I did some tests and it's working fine without errors so far. 

I'm using:

- CSI Version:
0.3.1

- Kubernetes Version:
1.12.0

- Cloud provider/framework version, if applicable (such as Rancher):
Rancher 2.1.1

**Comment by fatih** [comment]
@devfelipereis I see a mail with your comment from you but it's not here. Did it got deleted somehow?

**Comment by devfelipereis** [comment]
@fatih yes.

Yesterday I was testing rancher 2.1.1 with kuberntes 1.12.0. This plugin is working fine but I just tested with one node.

Then I post here but I want to test more today. With two nodes and some different stacks.

Then I'll post the results to not make spam with comments :)
